### ISSUE TITLE
Oauth version of registration form

### ISSUE THREAD

**Issue by srallen** [zooniverse/edu-api-front-end#10]
Can we think about having a modal dialog to present the options of either registering with Panoptes (which will link them to the standard oauth devise registration form) or the option of signing in with google? I think just immediately sending people to the devise registration form will be confusing to people why they're going off-site. For I2A we want to encourage folks to sign in with their Edu Google accounts (many universities here use Google Apps for Edu) because one of the feedback items we've received is that instructors and students really hate signing up for extra/new accounts. If we can bypass that one setup and directly provide the sign in with google link here, that might save us some headaches and complaints.

**Comment by shaunanoordin** [comment]
This idea makes a lot of sense, but I've never seen a non-Zooniverse login working in conjunction with a Zooniverse project. My thoughts at the moment:
* Do we have an example of this in action? i.e. using Google to login to a Zoo project?
* If not, who's best able to give an idea of a dev plan? Cam/Marten/Zach?
* Would there be any issues with the EduAPI? (i.e. linking Classrooms/Assignments to non-Zoo IDs)

**Comment by srallen** [comment]
Yep, this would be the first project that uses a feature that Panoptes has always mostly supported.

Log in with google was fixed in zooniverse/Panoptes#1865, however, it works on production, but not staging at the moment (see zooniverse/Panoptes#2024). I don't think there will be any issue because the way it works as I understand it is that when you log in with your Google account, it asks your permission to use your Google login credentials. Then basically, a Panoptes account is setup using those credentials. 

What I'm proposing here is mostly cosmetic. Just based on the feedback I've received, instructors may find the redirect to Panoptes' devise views (https://panoptes.zooniverse.org/users/sign_in) jarring and confusing, so it would be ideal if I can link directly to the Google sign-in via Panoptes' devise setup.

**Comment by camallen** [comment]
I'm pretty sure google has to redirect back to https://signin.zooniverse.org to complete the registration and I'm not sure we can support this in an iFrame (worth checking though). 

Normal flow is this:
  1. Click https://signin.zooniverse.org/users/sign_up (probably need to modify the redirect_uri for this domain)
  0. Click Sign In with google (doesn't work with signin, only with panotpes.zooniverse.org)
  0. Allow zooniverse to access google account
  0. Redirect back to Zooniverse to complete registration process

AFAIK we don't provide a mechanism to redirect back to an external site once the signup is completed. Using an iFrame would enable this to be done in a modal but it's not a great experience, maybe we should provide a way to redirect back to the source domain after successful signup?

**Comment by srallen** [comment]
Ok, I think I'd like to explore an iframe option. I know it's not ideal, but just based on the feedback I have gotten, I'd like to avoid the confusion of going off site for sign in. Being able to redirect back to the source domain would also be a good option.

**Comment by srallen** [comment]
I decided against the iframe and have made a modal just for sign in that includes a sign in or register button that links to the normal devise views from Panoptes and a sign in with google button that links directly to the Panoptes sign in with google route. Before the sign in is called, I store where the user was last in localStorage and so when they are redirected back to the site by Panoptes, I'm checking for the presence of that localStorage property and redirecting back to where the user was last. This is helpful for the join classrooms page.
