### ISSUE TITLE
Issues with joining classroom after signing in.

### ISSUE THREAD

**Issue by codydirks** [zooniverse/edu-api-front-end#121]
When clicking a join classroom link, I'm prompted to sign in to my Zooniverse account - but after signing in I'm re-directed to the classrooms.zooniverse.org homepage without any indication of whether or not I successfully joined. Clicking the link again opens up a new tab where I'm not signed in, leading to the same issue all over again. I'm not sure if this is the intended behavior (i.e. not maintaining signed-in status across tabs). 

The current solution is to sign in, let it redirect to the classrooms.zooniverse.org page, and then copy/paste the link into the address bar of that specific tab. Would prefer to have feedback after the sign-in completes, and/or automatically re-try to join the classroom after signing in.

**Comment by srallen** [comment]
I'm looking into this. This is not intended behavior. What should be happening is that you remain on the join page for confirmation.
