### ISSUE TITLE
Data Export Problem for Classroom.Zooniverse.org Galaxy Zoo 101

### ISSUE THREAD

**Issue by trouille** [zooniverse/edu-api-front-end#148]
@srallen I just got an email from Rose Finn using classroom.zooniverse in her Astro101 course. She used it last year as well. 

She's run into a data export error. 

Here's her info:
my username is Rose_Finn (rfinn@siena.edu).  My class for this spring is
https://classroom.zooniverse.org/#/astro-101-with-galaxy-zoo/students/classrooms/2673/join?token=7b9a17456a3f1962

and this is the project page for galaxy zoo
https://www.zooniverse.org/projects/zooniverse/galaxy-zoo-in-astronomy-101/classify?group=1749049&_ga=2.195639468.1877613624.1553048722-149825245.1553048722

If I go to https://www.zooniverse.org/lab/2308/data-exports - is there a workflow I can choose to export data and maybe manually pull out her classrooms data? Or other way that I can try to help her (without imposing on your time this week)?

**Comment by trouille** [comment]
Here's the error she gets: 
![Screen Shot 2019-03-20 at 11 31 10 AM](https://user-images.githubusercontent.com/4975655/54704258-62bebe00-4b08-11e9-8eb4-a0eedaa20e78.png)

**Comment by srallen** [comment]
These are caesar exports, so this indicates and issue with those. We can follow up in those logs looking for reductions exports for that user group id and those project's workflows that failed.

**Comment by srallen** [comment]
Fwiw, we can't really use Panoptes classification exports without doing manually the aggregation caesar does for those to make them usable.

**Comment by trouille** [comment]
Thanks! (And good reminder that caesar manipulates the data to make it more useable - so not that helpful to get the panoptes raw classification export)

I can ask Amy to check on caesar -- but to be sure I know what to ask for (also so I know for future cases) - are these the right numbers to share with Amy?: 
workflow = 2673
group ID = 1749049
?

**Comment by trouille** [comment]
(I'll share the full URLs w/ her, but it's for my knowledge as well).

**Comment by srallen** [comment]
The workflow ids are:
Galaxy Zoo 101: 5521
Hubble's Law: 5522

And user group id is correct, 1749049

(id 2673 is the classroom id which is only used by edu api, not by panoptes or caesar)

**Comment by trouille** [comment]
@srallen See https://github.com/zooniverse/caesar/issues/721

Looking like the classroom.zooniverse button for 'data exports' isn't acting as expected. No caesar calls were made by Rose's request (nor mine, that I tried today), as far as Amy was able to see.

**Comment by trouille** [comment]
But don't follow up at this time - for Rose, I'll just use example data exports that Tommy/Cody created previously. We'll address this problem this summer when Molly joins in June and we kick off the next round of classroom.zooniverse effort.

**Comment by srallen** [comment]
Closed by #158
