### ISSUE TITLE
Create exports for new Galaxy Zoo 101 Activity 

### ISSUE THREAD

**Issue by mollysimon** [zooniverse/edu-api-front-end#177]
I have updated the original galaxy zoo activity from classroom.zooniverse so the exports now have to be reconfigured for the new activity.

Here is a link to the project:
https://www.zooniverse.org/projects/mollysimon/galaxy-zoo-crowdsourcing-activity

Thanks so much for your help!

**Comment by srallen** [comment]
this is done.
