### ISSUE TITLE
Make a Pretty Home Page

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/edu-api-front-end#28]
## Feature Required
* Currently the Edu API Home page is a very very basic link to I2A and WildCam Darien.
![screen shot 2017-08-18 at 19 57 56](https://user-images.githubusercontent.com/13952701/29473620-602972fa-8450-11e7-81d0-d81e52cd98bd.png)
* We'll want to make this look somewhat more presentable before our Beta users start coming in - even if we're not going to wow them with a perfect design, we should at least present a good first impression.
* Ideally we'll be able to revisit this "Zooniverse Education" brand better in the future and properly think of how we want to present new Teachers/Students who visits the site.

### Suggestion:
* Use a listing of Card components: https://grommet.github.io/docs/card

**Comment by shaunanoordin** [comment]
Baseline has been addressed by PR #32 , but that still needs further work.

**Comment by srallen** [comment]
Leaving open because we should sort the classrooms on the home page so they show up in a consistent order.
