### ISSUE TITLE
Signed in classroom view for I2A

### ISSUE THREAD

**Issue by srallen** [zooniverse/edu-api-front-end#6]

**Comment by shaunanoordin** [comment]
Question: is the Signed In Classroom View referred to in this Issue aimed at Teachers (i.e. an admin view/page to manage Classrooms and Assignments) or at Students (i.e. something the Teacher presents to the whole class on a projector)?

For comparison, the 'views' (or rather, tasks/features) used by WildCam Gorongosa Lab (and hence WildCam Darien Lab) are:
* (Teachers)
  * Register self (one-off)
  * Add a Classroom
  * List all my Classrooms
  * Examine a single Classroom (also Edit, Delete)
    * Add an Assignment
    * List all Assignments in a Classroom
    * Examine a single Assignment (also Edit, Delete)
* (Students)
  * List all my Assignments
* (Both)
  * View Map Explorer

I ask because, if we can find where the overlap is, we can better design the common components to be used in I2A and WildCam Darien.

e.g. something like
```
<I2A_Teachers>
  <ClassroomManager />
  <AssignmentManager>
    <GeneralAssignment />
  </Assignment>
</I2A_Teachers>
```
and
```
<WildCamDarien_Teachers>
  <ClassroomManager />
  <AssignmentManager>
    <SurveyTaskAssignment />
  </AssignmentManager>
  <MapExplorer>
</WildCamDarien_Teachers>
```

**Comment by srallen** [comment]
I do think we should find overlap. Here's the invision for the I2A classroom management: https://projects.invisionapp.com/d/#/console/10495701/240875082/preview

Here's an annotated view with the intended functionality I just made: 
<img width="1067" alt="screen shot 2017-07-31 at 10 38 42 am" src="https://user-images.githubusercontent.com/5016731/28786305-7757373a-75de-11e7-8920-c1dedb0c9698.png">

I2A will not have a student view. This is based on early pilot feedback from instructors. Students do not want to go to another web app to get course related content in addition to whatever their university has setup for them for the course. Therefore, we're generating the links instructors should share and it is their responsibility to share that content with the students, through email or posted to a LMS like Blackboard. 

For I2A, the data export from caesar will be a CSV that can either be downloaded or opened in google sheets (the export link will open options for this either inline or in a modal). All of the I2A data exploration activities are designed to happen in google sheets and use the [zootools-sheets](https://github.com/zooniverse/zootools-sheets) add-on. 

For the instructor view, if the above design mostly works for both projects which I think it will, then we can build out a shared component(s) that handles the common functionality of creating a classroom, generating the project assignment link, etc.

**Comment by srallen** [comment]
To follow up, I was slightly incorrect about the expanded student list progress view. Here is the design for it: https://projects.invisionapp.com/d/main#/console/10495701/240875083/preview

The `Export Grades` button will just grab those student usernames, the percentage complete stat and put that in a CSV. This is something I think we could just do w/ javascript. This is not a core requirement though, since it's really only there to support instructors who want to use these completion stats in their own excel files for grading.

**Comment by srallen** [comment]
A prototype of the classrooms list view is done. For the classroom details view, here is the design: 
https://projects.invisionapp.com/share/9GD3P20BP#/screens

This design really is for the I2A use case since we have 3 auto-created assignments on classroom create, so it makes sense for I2A, but will need modification for WD use. I'm not sure what @beckyrother's schedule is for next week, but we can possibly come up with a prototype on our own for the WD use case. Aside from that, the view will need minor adjustments:
- [ ] The student username and display name should probably be one column that shows the zooniverse username or display name if available. We cannot guarantee the student will fill in the display name for their profile. 
- [ ] The copy join link button here could show a full preview of the URL that can then be copied. Perhaps the copy button functionality could be abstracted out into its own component and have a boolean prop that can be set to render the full url preview or not?
- [ ] There needs to be an edit button that opens up the modal form with the current field values for editing.
- [ ] And just to add to the list for completeness the note about the Export Grades button: It will just grab those student usernames, the percentage complete stat and put that in a CSV. This is something I think we could just do w/ javascript. This is not a core requirement though, since it's really only there to support instructors who want to use these completion stats in their own excel files for grading.

**Comment by srallen** [comment]
I'm going to close this and open specific issues about what is left to do.
